# Generated by Django 4.1 on 2022-12-07 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('name', models.CharField(help_text='image name', max_length=50, primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to='upload/')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('img_new', models.TextField(max_length=512)),
            ],
        ),
    ]
